### ISSUE TITLE
flags not working

### ISSUE THREAD

**Issue by hacktorious** [hexorx/countries#489]
I'm currently having an issue with flags not working in certain environments.  For example, they work on MacOSX, but not in windows or on Ubuntu.  How can I fix this?

**Comment by DaniG2k** [comment]
I also cannot get flags working on MacOS High Sierra.
I am trying with:

```Country['MY'].emoji_flag
NoMethodError: undefined method `emoji_flag' for #<Country:0x007fafa4ee27c0>```

Any advice on how to fix?

**Comment by rposborne** [comment]
@DaniG2k I am not able to reproduce on my MacOS High Sierra Machine.
```
[3] pry(main)> require 'countries/global'
=> true
[4] pry(main)> Country['MY'].emoji_flag
=> "🇲🇾"
```

@hacktorious  How are they breaking? Saying they don't work doesn't provide much data to go on. 

Running inside a docker copy of ubuntu I am able to see the respective codepoints for the emojis.

```
[1] pry(main)> require 'countries/global'
=> true
[2] pry(main)> Country['MY'].emoji_flag
=> "\u{1F1F2}\u{1F1FE}"
```

**Comment by DaniG2k** [comment]
@rposborne I just installed the latest version (0.11.5). Here's what I see:

```
2.2.2 :003 > require 'countries'
 => false

2.2.2 :004 > require 'countries/global'
LoadError: cannot load such file -- countries/global
        from /Users/myUser/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
        from /Users/myUser/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
        from /Users/myUser/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /Users/myUser/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
        from (irb):4
        from /Users/myUser/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/commands/console.rb:110:in `start'
        from /Users/myUser/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in `start'
        from /Users/myUser/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /Users/myUser/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /Users/myUser/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:8:in `require'
        from bin/rails:8:in `<main>'

2.2.2 :005 > Country['MY'].emoji_flag
NoMethodError: undefined method `emoji_flag' for #<Country:0x007f9fadcdc3d8>
        from (irb):5
        from /Users/myUser/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/commands/console.rb:110:in `start'
        from /Users/myUser/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in `start'
        from /Users/myUser/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /Users/myUser/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /Users/myUser/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:8:in `require'
        from bin/rails:8:in `<main>'
```

Please let me know if I can provide additional info to debug.

**Comment by rposborne** [comment]
ah @DaniG2k 0.11.5 is very old. The current release is 2.1.8 

https://rubygems.org/gems/countries

**Comment by rposborne** [comment]
Apologies hit the wrong button.

**Comment by DaniG2k** [comment]
Ah my bad then. I didn't realize I was that far behind. Unfortunately I cannot use that gem on the project I'm working down because a slew of other gems (money, money-rails, nokogiri, capybara, poltergeist, etc) will all require an update as a consequence. No worries in that case, I just thought it was a bug but I'm happy to have this closed.

**Comment by hacktorious** [comment]
They appear as text not a flag.  (ie - BZ for Brazil instead of a flag)

**Comment by awilkening** [comment]
We are using version 7.1.1 with Rails 7.2.1. The emoji_flag method works for mac users using Chrome Version 133.0.6943.100, however, Windows users using the latest version of Chrome are getting the text instead.
